<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Deepak-Sharma1" ignored="0" name="TestCase1" tests="9" failures="3" timestamp="27 Jun 2019 15:31:12 GMT" time="0.101" errors="0">
  <testcase name="mytest1" time="0.014" classname="com.pfl.automation.org62.testcases.RuntimeRetryTest">
    <skipped/>
  </testcase> <!-- mytest1 -->
  <testcase name="mytest1" time="0.002" classname="com.pfl.automation.org62.testcases.RuntimeRetryTest">
    <skipped/>
  </testcase> <!-- mytest1 -->
  <testcase name="mytest1" time="0.002" classname="com.pfl.automation.org62.testcases.RuntimeRetryTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.pfl.automation.org62.testcases.RuntimeRetryTest.mytest1(RuntimeRetryTest.java:12)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- mytest1 -->
  <testcase name="mytest2" time="0.003" classname="com.pfl.automation.org62.testcases.RuntimeRetryTest">
    <skipped/>
  </testcase> <!-- mytest2 -->
  <testcase name="mytest2" time="0.002" classname="com.pfl.automation.org62.testcases.RuntimeRetryTest">
    <skipped/>
  </testcase> <!-- mytest2 -->
  <testcase name="mytest2" time="0.001" classname="com.pfl.automation.org62.testcases.RuntimeRetryTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.pfl.automation.org62.testcases.RuntimeRetryTest.mytest2(RuntimeRetryTest.java:18)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- mytest2 -->
  <testcase name="mytest3" time="0.006" classname="com.pfl.automation.org62.testcases.RuntimeRetryTest">
    <skipped/>
  </testcase> <!-- mytest3 -->
  <testcase name="mytest3" time="0.002" classname="com.pfl.automation.org62.testcases.RuntimeRetryTest">
    <skipped/>
  </testcase> <!-- mytest3 -->
  <testcase name="mytest3" time="0.002" classname="com.pfl.automation.org62.testcases.RuntimeRetryTest">
    <failure type="java.lang.AssertionError" message="expected [Sharma] but found [Deepak]">
      <![CDATA[java.lang.AssertionError: expected [Sharma] but found [Deepak]
at com.pfl.automation.org62.testcases.RuntimeRetryTest.mytest3(RuntimeRetryTest.java:24)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- mytest3 -->
</testsuite> <!-- TestCase1 -->
